version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    container_name: resumetry-frontend
    restart: unless-stopped
    networks:
      - resumetry-network

networks:
  resumetry-network:
    driver: bridge

